# Generated by Django 4.2.3 on 2023-09-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagestore', '0009_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
