# Generated by Django 4.2.1 on 2023-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagestore', '0013_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
