# Generated by Django 4.2.1 on 2023-10-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagestore', '0017_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
